const indianCities = [
  { city: "Mumbai", state: "Maharashtra", postalCode: "400001" },
  { city: "Delhi", state: "Delhi", postalCode: "110001" },
  { city: "Bengaluru", state: "Karnataka", postalCode: "560001" },
  { city: "Kolkata", state: "West Bengal", postalCode: "700001" },
  { city: "Chennai", state: "Tamil Nadu", postalCode: "600001" },
  { city: "Hyderabad", state: "Telangana", postalCode: "500001" },
  { city: "Ahmedabad", state: "Gujarat", postalCode: "380001" },
  { city: "Pune", state: "Maharashtra", postalCode: "411001" },
  { city: "Surat", state: "Gujarat", postalCode: "395001" },
  { city: "Jaipur", state: "Rajasthan", postalCode: "302001" },
  { city: "Lucknow", state: "Uttar Pradesh", postalCode: "226001" },
  { city: "Kanpur", state: "Uttar Pradesh", postalCode: "208001" },
  { city: "Nagpur", state: "Maharashtra", postalCode: "440001" },
  { city: "Indore", state: "Madhya Pradesh", postalCode: "452001" },
  { city: "Thane", state: "Maharashtra", postalCode: "400601" },
  { city: "Bhopal", state: "Madhya Pradesh", postalCode: "462001" },
  { city: "Visakhapatnam", state: "Andhra Pradesh", postalCode: "530001" },
  { city: "Patna", state: "Bihar", postalCode: "800001" },
  { city: "Vadodara", state: "Gujarat", postalCode: "390001" },
  { city: "Ghaziabad", state: "Uttar Pradesh", postalCode: "201001" },
  { city: "Ludhiana", state: "Punjab", postalCode: "141001" },
  { city: "Agra", state: "Uttar Pradesh", postalCode: "282001" },
  { city: "Nashik", state: "Maharashtra", postalCode: "422001" },
  { city: "Faridabad", state: "Haryana", postalCode: "121001" },
  { city: "Meerut", state: "Uttar Pradesh", postalCode: "250001" },
  { city: "Rajkot", state: "Gujarat", postalCode: "360001" },
  { city: "Kalyan-Dombivli", state: "Maharashtra", postalCode: "421201" },
  { city: "Vasai-Virar", state: "Maharashtra", postalCode: "401202" },
  { city: "Varanasi", state: "Uttar Pradesh", postalCode: "221001" },
  { city: "Srinagar", state: "Jammu and Kashmir", postalCode: "190001" },
  { city: "Aurangabad", state: "Maharashtra", postalCode: "431001" },
  { city: "Dhanbad", state: "Jharkhand", postalCode: "826001" },
  { city: "Amritsar", state: "Punjab", postalCode: "143001" },
  { city: "Navi Mumbai", state: "Maharashtra", postalCode: "400703" },
  { city: "Allahabad", state: "Uttar Pradesh", postalCode: "211001" },
  { city: "Ranchi", state: "Jharkhand", postalCode: "834001" },
  { city: "Howrah", state: "West Bengal", postalCode: "711101" },
  { city: "Coimbatore", state: "Tamil Nadu", postalCode: "641001" },
  { city: "Jabalpur", state: "Madhya Pradesh", postalCode: "482001" },
  { city: "Gwalior", state: "Madhya Pradesh", postalCode: "474001" },
  { city: "Vijayawada", state: "Andhra Pradesh", postalCode: "520001" },
  { city: "Jodhpur", state: "Rajasthan", postalCode: "342001" },
  { city: "Madurai", state: "Tamil Nadu", postalCode: "625001" },
  { city: "Raipur", state: "Chhattisgarh", postalCode: "492001" },
  { city: "Kota", state: "Rajasthan", postalCode: "324001" },
  { city: "Guwahati", state: "Assam", postalCode: "781001" },
  { city: "Chandigarh", state: "Chandigarh", postalCode: "160001" },
  { city: "Solapur", state: "Maharashtra", postalCode: "413001" },
  { city: "Salem", state: "Tamil Nadu", postalCode: "636001" },
  { city: "Tiruchirappalli", state: "Tamil Nadu", postalCode: "620001" },
  { city: "Tiruppur", state: "Tamil Nadu", postalCode: "641601" },
  { city: "Erode", state: "Tamil Nadu", postalCode: "638001" },
  { city: "Vellore", state: "Tamil Nadu", postalCode: "632001" },
  { city: "Tirunelveli", state: "Tamil Nadu", postalCode: "627001" },
  { city: "Thoothukudi", state: "Tamil Nadu", postalCode: "628001" },
  { city: "Dindigul", state: "Tamil Nadu", postalCode: "624001" },
  { city: "Thanjavur", state: "Tamil Nadu", postalCode: "613001" },
  { city: "Cuddalore", state: "Tamil Nadu", postalCode: "607001" },
  { city: "Nagercoil", state: "Tamil Nadu", postalCode: "629001" },
  { city: "Kanchipuram", state: "Tamil Nadu", postalCode: "631501" },
  { city: "Kumbakonam", state: "Tamil Nadu", postalCode: "612001" },
  { city: "Nagapattinam", state: "Tamil Nadu", postalCode: "611001" },
  { city: "Udhagamandalam", state: "Tamil Nadu", postalCode: "643001" },
  { city: "Pudukkottai", state: "Tamil Nadu", postalCode: "622001" },
  { city: "Ariyalur", state: "Tamil Nadu", postalCode: "621704" },
  { city: "Karur", state: "Tamil Nadu", postalCode: "639001" },
  { city: "Perambalur", state: "Tamil Nadu", postalCode: "621212" },
  { city: "Sivakasi", state: "Tamil Nadu", postalCode: "626123" },
  { city: "Tenkasi", state: "Tamil Nadu", postalCode: "627811" },
  { city: "Namakkal", state: "Tamil Nadu", postalCode: "637001" },
  { city: "Ramanathapuram", state: "Tamil Nadu", postalCode: "623501" },
  { city: "Virudhunagar", state: "Tamil Nadu", postalCode: "626001" },
  { city: "Viluppuram", state: "Tamil Nadu", postalCode: "605602" },
  { city: "Krishnagiri", state: "Tamil Nadu", postalCode: "635001" },
  { city: "Dharmapuri", state: "Tamil Nadu", postalCode: "636701" },
  { city: "Karaikkudi", state: "Tamil Nadu", postalCode: "630001" },
  { city: "Hosur", state: "Tamil Nadu", postalCode: "635109" },
  { city: "Ambur", state: "Tamil Nadu", postalCode: "635802" },
  { city: "Arakkonam", state: "Tamil Nadu", postalCode: "631001" },
  { city: "Tindivanam", state: "Tamil Nadu", postalCode: "604001" },
  { city: "Thiruvarur", state: "Tamil Nadu", postalCode: "610001" },
  { city: "Mayiladuthurai", state: "Tamil Nadu", postalCode: "609001" },
  { city: "Pattukkottai", state: "Tamil Nadu", postalCode: "614601" },
  { city: "Rameswaram", state: "Tamil Nadu", postalCode: "623526" },
  { city: "Paramakudi", state: "Tamil Nadu", postalCode: "623707" },
  { city: "Manamadurai", state: "Tamil Nadu", postalCode: "630606" },
  { city: "Sivaganga", state: "Tamil Nadu", postalCode: "630561" },
  { city: "Palani", state: "Tamil Nadu", postalCode: "624601" },
  { city: "Mettupalayam", state: "Tamil Nadu", postalCode: "641301" },
  { city: "Palladam", state: "Tamil Nadu", postalCode: "641664" },
  { city: "Pollachi", state: "Tamil Nadu", postalCode: "642001" },
  { city: "Avinashi", state: "Tamil Nadu", postalCode: "641654" },
  { city: "Mettur", state: "Tamil Nadu", postalCode: "636401" },
  { city: "Attur", state: "Tamil Nadu", postalCode: "636102" },
  { city: "Kallakurichi", state: "Tamil Nadu", postalCode: "606202" },
  { city: "Sankarankovil", state: "Tamil Nadu", postalCode: "627756" },
  { city: "Tirupathur", state: "Tamil Nadu", postalCode: "635601" },
  { city: "Oddanchatram", state: "Tamil Nadu", postalCode: "624619" },
  { city: "Bodinayakkanur", state: "Tamil Nadu", postalCode: "625513" },
  { city: "Theni", state: "Tamil Nadu", postalCode: "625531" },
  { city: "Usilampatti", state: "Tamil Nadu", postalCode: "625532" },
  { city: "Chengalpattu", state: "Tamil Nadu", postalCode: "603001" },
  { city: "Sathyamangalam", state: "Tamil Nadu", postalCode: "638402" },
  { city: "Valparai", state: "Tamil Nadu", postalCode: "642127" },
  { city: "Coonoor", state: "Tamil Nadu", postalCode: "643102" },
  { city: "Gudiyatham", state: "Tamil Nadu", postalCode: "632602" },
  { city: "Neyveli", state: "Tamil Nadu", postalCode: "607803" },
  { city: "Kovilpatti", state: "Tamil Nadu", postalCode: "628501" },
  { city: "Nagercoil", state: "Tamil Nadu", postalCode: "629001" },
  { city: "Rajapalayam", state: "Tamil Nadu", postalCode: "626117" },
  { city: "Arani", state: "Tamil Nadu", postalCode: "632301" },
  { city: "Jayankondam", state: "Tamil Nadu", postalCode: "621802" },
  { city: "Sivakasi", state: "Tamil Nadu", postalCode: "626123" },
  { city: "Thuraiyur", state: "Tamil Nadu", postalCode: "621010" },
  { city: "Tiruttani", state: "Tamil Nadu", postalCode: "631209" },
  { city: "Uthamapalayam", state: "Tamil Nadu", postalCode: "625533" },
  { city: "Udumalaipettai", state: "Tamil Nadu", postalCode: "642126" },
  { city: "Arakkonam", state: "Tamil Nadu", postalCode: "631001" },
  { city: "Viluppuram", state: "Tamil Nadu", postalCode: "605602" },
  { city: "Vaniyambadi", state: "Tamil Nadu", postalCode: "635751" },
  { city: "Tiruvannamalai", state: "Tamil Nadu", postalCode: "606601" },
  { city: "Tiruvallur", state: "Tamil Nadu", postalCode: "602001" },
  { city: "Tambaram", state: "Tamil Nadu", postalCode: "600045" },
  { city: "Perundurai", state: "Tamil Nadu", postalCode: "638052" },
  { city: "Pennadam", state: "Tamil Nadu", postalCode: "606105" },
  { city: "Panruti", state: "Tamil Nadu", postalCode: "607106" },
  { city: "Ooty", state: "Tamil Nadu", postalCode: "643001" },
  { city: "Nilgiris", state: "Tamil Nadu", postalCode: "643223" },
  { city: "Nagari", state: "Tamil Nadu", postalCode: "517590" },
  { city: "Mayiladuthurai", state: "Tamil Nadu", postalCode: "609001" },
  { city: "Manapparai", state: "Tamil Nadu", postalCode: "621306" },
  { city: "Karur", state: "Tamil Nadu", postalCode: "639001" },
  { city: "Kanyakumari", state: "Tamil Nadu", postalCode: "629702" },
  { city: "Karaikudi", state: "Tamil Nadu", postalCode: "630001" },
  { city: "Kancheepuram", state: "Tamil Nadu", postalCode: "631501" },
  { city: "Kallakurichi", state: "Tamil Nadu", postalCode: "606202" },
  { city: "Kallidaikurichi", state: "Tamil Nadu", postalCode: "627416" },
  { city: "Karaikal", state: "Tamil Nadu", postalCode: "609602" },
  { city: "Kovilpatti", state: "Tamil Nadu", postalCode: "628501" },
  { city: "Kumbakonam", state: "Tamil Nadu", postalCode: "612001" },
  { city: "Kulithalai", state: "Tamil Nadu", postalCode: "639104" },
  { city: "Kadayanallur", state: "Tamil Nadu", postalCode: "627751" },
  { city: "Namakkal", state: "Tamil Nadu", postalCode: "637001" },
  { city: "Nanguneri", state: "Tamil Nadu", postalCode: "627108" },
  { city: "Nagercoil", state: "Tamil Nadu", postalCode: "629001" },
  { city: "Nagapattinam", state: "Tamil Nadu", postalCode: "611001" },
  { city: "Manali", state: "Tamil Nadu", postalCode: "600068" },
  { city: "Manachanallur", state: "Tamil Nadu", postalCode: "621005" },
  { city: "Mettur", state: "Tamil Nadu", postalCode: "636401" },
  { city: "Mettupalayam", state: "Tamil Nadu", postalCode: "641301" },
  { city: "Mannargudi", state: "Tamil Nadu", postalCode: "614001" },
  { city: "Mangadu", state: "Tamil Nadu", postalCode: "600122" },
  { city: "Mettupalayam", state: "Tamil Nadu", postalCode: "641301" },
  { city: "Madurantakam", state: "Tamil Nadu", postalCode: "603306" },
  { city: "Vedaranyam", state: "Tamil Nadu", postalCode: "614810" },
  { city: "Udumalpet", state: "Tamil Nadu", postalCode: "642126" },
  { city: "Turaiyur", state: "Tamil Nadu", postalCode: "621010" },
  { city: "Tiruppur", state: "Tamil Nadu", postalCode: "641601" },
  { city: "Tirupathur", state: "Tamil Nadu", postalCode: "635601" },
  { city: "Tiruttani", state: "Tamil Nadu", postalCode: "631209" },
  { city: "Tiruchirappalli", state: "Tamil Nadu", postalCode: "620001" },
  { city: "Tenkasi", state: "Tamil Nadu", postalCode: "627811" },
  { city: "Tambaram", state: "Tamil Nadu", postalCode: "600045" },
  { city: "Srivilliputhur", state: "Tamil Nadu", postalCode: "626125" },
  { city: "Sivakasi", state: "Tamil Nadu", postalCode: "626123" },
  { city: "Sivaganga", state: "Tamil Nadu", postalCode: "630561" },
  { city: "Sattur", state: "Tamil Nadu", postalCode: "626203" },
  { city: "Rameswaram", state: "Tamil Nadu", postalCode: "623526" },
  { city: "Rajapalayam", state: "Tamil Nadu", postalCode: "626117" },
  { city: "Perundurai", state: "Tamil Nadu", postalCode: "638052" },
  { city: "Thiruvananthapuram", state: "Kerala", postalCode: "695001" },
  { city: "Kochi", state: "Kerala", postalCode: "682001" },
  { city: "Kozhikode", state: "Kerala", postalCode: "673001" },
  { city: "Thrissur", state: "Kerala", postalCode: "680001" },
  { city: "Kollam", state: "Kerala", postalCode: "691001" },
  { city: "Alappuzha", state: "Kerala", postalCode: "688001" },
  { city: "Kannur", state: "Kerala", postalCode: "670001" },
  { city: "Kottayam", state: "Kerala", postalCode: "686001" },
  { city: "Palakkad", state: "Kerala", postalCode: "678001" },
  { city: "Malappuram", state: "Kerala", postalCode: "676505" },
  { city: "Pathanamthitta", state: "Kerala", postalCode: "689645" },
  { city: "Kasaragod", state: "Kerala", postalCode: "671121" },
  { city: "Wayanad", state: "Kerala", postalCode: "673122" },
  { city: "Thalassery", state: "Kerala", postalCode: "670101" },
  { city: "Ponnani", state: "Kerala", postalCode: "679577" },
  { city: "Manjeri", state: "Kerala", postalCode: "676121" },
  { city: "Neyyattinkara", state: "Kerala", postalCode: "695121" },
  { city: "Vadakara", state: "Kerala", postalCode: "673101" },
  { city: "Koyilandy", state: "Kerala", postalCode: "673305" },
  { city: "Tirur", state: "Kerala", postalCode: "676101" },
  { city: "Nedumangad", state: "Kerala", postalCode: "695541" },
  { city: "Thiruvalla", state: "Kerala", postalCode: "689101" },
  { city: "Kottarakkara", state: "Kerala", postalCode: "691506" },
  { city: "Perinthalmanna", state: "Kerala", postalCode: "679322" },
  { city: "Chalakudy", state: "Kerala", postalCode: "680307" },
  { city: "Visakhapatnam", state: "Andhra Pradesh", postalCode: "530001" },
  { city: "Vijayawada", state: "Andhra Pradesh", postalCode: "520001" },
  { city: "Guntur", state: "Andhra Pradesh", postalCode: "522001" },
  { city: "Nellore", state: "Andhra Pradesh", postalCode: "524001" },
  { city: "Kurnool", state: "Andhra Pradesh", postalCode: "518001" },
  { city: "Rajahmundry", state: "Andhra Pradesh", postalCode: "533101" },
  { city: "Tirupati", state: "Andhra Pradesh", postalCode: "517501" },
  { city: "Kakinada", state: "Andhra Pradesh", postalCode: "533001" },
  { city: "Anantapur", state: "Andhra Pradesh", postalCode: "515001" },
  { city: "Eluru", state: "Andhra Pradesh", postalCode: "534001" },
  { city: "Vizianagaram", state: "Andhra Pradesh", postalCode: "535001" },
  { city: "Ongole", state: "Andhra Pradesh", postalCode: "523001" },
  { city: "Tenali", state: "Andhra Pradesh", postalCode: "522201" },
  { city: "Nandyal", state: "Andhra Pradesh", postalCode: "518501" },
  { city: "Proddatur", state: "Andhra Pradesh", postalCode: "516360" },
  { city: "Adoni", state: "Andhra Pradesh", postalCode: "518301" },
  { city: "Madanapalle", state: "Andhra Pradesh", postalCode: "517325" },
  { city: "Chittoor", state: "Andhra Pradesh", postalCode: "517001" },
  { city: "Hindupur", state: "Andhra Pradesh", postalCode: "515201" },
  { city: "Bhimavaram", state: "Andhra Pradesh", postalCode: "534201" },
  { city: "Srikakulam", state: "Andhra Pradesh", postalCode: "532001" },
  { city: "Guntakal", state: "Andhra Pradesh", postalCode: "515801" },
  { city: "Dharmavaram", state: "Andhra Pradesh", postalCode: "515671" },
  { city: "Gudivada", state: "Andhra Pradesh", postalCode: "521301" },
  { city: "Machilipatnam", state: "Andhra Pradesh", postalCode: "521001" },
  { city: "Bengaluru", state: "Karnataka", postalCode: "560001" },
  { city: "Hubballi", state: "Karnataka", postalCode: "580020" },
  { city: "Mysuru", state: "Karnataka", postalCode: "570001" },
  { city: "Mangaluru", state: "Karnataka", postalCode: "575001" },
  { city: "Belagavi", state: "Karnataka", postalCode: "590001" },
  { city: "Kalaburagi", state: "Karnataka", postalCode: "585102" },
  { city: "Ballari", state: "Karnataka", postalCode: "583101" },
  { city: "Vijayapura", state: "Karnataka", postalCode: "586101" },
  { city: "Bidar", state: "Karnataka", postalCode: "585401" },
  { city: "Davanagere", state: "Karnataka", postalCode: "577001" },
  { city: "Gulbarga", state: "Karnataka", postalCode: "585102" },
  { city: "Shivamogga", state: "Karnataka", postalCode: "577201" },
  { city: "Tumakuru", state: "Karnataka", postalCode: "572101" },
  { city: "Raichur", state: "Karnataka", postalCode: "584101" },
  { city: "Hassan", state: "Karnataka", postalCode: "573201" },
  { city: "Chitradurga", state: "Karnataka", postalCode: "577501" },
  { city: "Kolar", state: "Karnataka", postalCode: "563101" },
  { city: "Udupi", state: "Karnataka", postalCode: "576101" },
  { city: "Robertson Pet", state: "Karnataka", postalCode: "563122" },
  { city: "Gadag-Betigeri", state: "Karnataka", postalCode: "582101" },
  { city: "Mandya", state: "Karnataka", postalCode: "571401" },
  { city: "Chikkamagaluru", state: "Karnataka", postalCode: "577101" },
  { city: "Hospet", state: "Karnataka", postalCode: "583201" },
  { city: "Chikkaballapura", state: "Karnataka", postalCode: "562101" },
  { city: "Ramanagara", state: "Karnataka", postalCode: "562159" },
  { city: "Hyderabad", state: "Telangana", postalCode: "500001" },
  { city: "Warangal", state: "Telangana", postalCode: "506002" },
  { city: "Nizamabad", state: "Telangana", postalCode: "503001" },
  { city: "Khammam", state: "Telangana", postalCode: "507003" },
  { city: "Karimnagar", state: "Telangana", postalCode: "505001" },
  { city: "Ramagundam", state: "Telangana", postalCode: "505208" },
  { city: "Mahbubnagar", state: "Telangana", postalCode: "509001" },
  { city: "Nalgonda", state: "Telangana", postalCode: "508001" },
  { city: "Adilabad", state: "Telangana", postalCode: "504001" },
  { city: "Suryapet", state: "Telangana", postalCode: "508213" },
  { city: "Miryalaguda", state: "Telangana", postalCode: "508207" },
  { city: "Jagtial", state: "Telangana", postalCode: "505327" },
  { city: "Kothagudem", state: "Telangana", postalCode: "507101" },
  { city: "Bodhan", state: "Telangana", postalCode: "503185" },
  { city: "Mancherial", state: "Telangana", postalCode: "504208" },
  { city: "Siddipet", state: "Telangana", postalCode: "502103" },
  { city: "Sircilla", state: "Telangana", postalCode: "505301" },
  { city: "Koratla", state: "Telangana", postalCode: "505326" },
  { city: "Wanaparthy", state: "Telangana", postalCode: "509103" },
  { city: "Kagaznagar", state: "Telangana", postalCode: "504001" },
  { city: "Palwancha", state: "Telangana", postalCode: "507115" },
  { city: "Jangaon", state: "Telangana", postalCode: "506167" },
  { city: "Kamareddy", state: "Telangana", postalCode: "503111" },
  { city: "Alampur", state: "Telangana", postalCode: "509152" },
  { city: "Bellampalli", state: "Telangana", postalCode: "504251" },
];
const uniqueCities = {};

// Iterate over the array and store each city name as a key in the uniqueCities object
indianCities.forEach((city) => {
  uniqueCities[city.city.toLowerCase()] = city;
});

// Convert the uniqueCities object back to an array
export const IndianCities = Object.values(uniqueCities);
